# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTk0MmY2YWUxYzMwNmI0MmFmODFiODNlYTlhY2IwMWU2OTI5NjY1OWJjZjdkNDcwYWZhNzY5MTQyYTNhMTZiNWY2MThhMDc1ODEyNTIzNGU2ZTBjNGI0OTZlMThlNGQxYTM1MTFiMzJhNWFlNGRhZDc4NjY5NDM1NDEzOGMxOTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
